### ISSUE TITLE
(Error in Window 11 Pro) OSError: cannot load library 'gobject-2.0-0': error 0x7e.  

### ISSUE THREAD

**Issue by datafyresearcher** [assafelovic/gpt-researcher#314] opened 2024-01-01 06:12 UTC
OSError: cannot load library 'gobject-2.0-0': error 0x7e.  Additionally, ctypes.util.find_library() did not manage to locate a library called 'gobject-2.0-0'

![OSError](https://github.com/assafelovic/gpt-researcher/assets/142796870/66e5fb3a-47f7-42ca-8ca1-1e5c316c34a4)

**Comment by datafyresearcher** [comment] 2024-01-01 06:13
**Any one have solution for this issue? Let me know about it.**

**Comment by sadiuysal** [comment] 2024-01-01 14:32
I'm having the same problem

**Comment by sadiuysal** [comment] 2024-01-01 15:30
I tried a couple of solutions and it seems the problem is related to some dependencies:
glib and pango

- brew install glib
- brew install pango
(you need to check those commands for your OS)

resolved the issue for me.

**Comment by assafelovic** [comment] 2024-01-03 13:02
Thanks for updating with resolution @sadiuysal !!

**Comment by aaaastark** [comment] 2024-01-03 22:15
# OSError: cannot load library 'gobject-2.0-0': error 0x7e.
---

## The error in Windows 11 Pro has been addressed through the information provided in the mentioned 'Issue.' Kindly follow the provided details to resolve the bugs.

- **Issue: OSError** - For Windows 11 Pro/Home users encountering the 'OSError: cannot load library 'gobject-2.0-0'' error, please refer to [this OSError GitHub issue](https://github.com/assafelovic/gpt-researcher/issues/314). To resolve this issue, install the `WeasyPrint` software on your local machine by using the [GTK for Windows Runtime Environment Installer](https://github.com/tschoonj/GTK-for-Windows-Runtime-Environment-Installer/releases/tag/2022-01-04).

@assafelovic @sadiuysal

**Comment by NicoLiendro14** [comment] 2024-05-02 00:42
> # OSError: cannot load library 'gobject-2.0-0': error 0x7e.
> ## The error in Windows 11 Pro has been addressed through the information provided in the mentioned 'Issue.' Kindly follow the provided details to resolve the bugs.
> 
>     * **Issue: OSError** - For Windows 11 Pro/Home users encountering the 'OSError: cannot load library 'gobject-2.0-0'' error, please refer to [this OSError GitHub issue](https://github.com/assafelovic/gpt-researcher/issues/314). To resolve this issue, install the `WeasyPrint` software on your local machine by using the [GTK for Windows Runtime Environment Installer](https://github.com/tschoonj/GTK-for-Windows-Runtime-Environment-Installer/releases/tag/2022-01-04).
> 
> 
> @assafelovic @sadiuysal

This works for me in Windows 10 Pro!

**Comment by sshenoy7** [comment] 2024-05-07 07:03
> sudo ln -s /opt/homebrew/opt/glib/lib/libgobject-2.0.0.dylib /usr/local/lib/gobject-2.0 sudo ln -s /opt/homebrew/opt/pango/lib/libpango-1.0.dylib /usr/local/lib/pango-1.0 sudo ln -s /opt/homebrew/opt/harfbuzz/lib/libharfbuzz.dylib /usr/local/lib/harfbuzz sudo ln -s /opt/homebrew/opt/fontconfig/lib/libfontconfig.1.dylib /usr/local/lib/fontconfig-1 sudo ln -s /opt/homebrew/opt/pango/lib/libpangoft2-1.0.dylib /usr/local/lib/pangoft2-1.0
> 
> refer to https://stackoverflow.com/questions/63449770/oserror-cannot-load-library-gobject-2-0-error-0x7e

@leafy1980 Thanks a lot buddy. This worked for me on Mac mini M1.

**Comment by assafelovic** [comment] 2024-06-12 06:24
Fixed in recent versions.

**Closed by assafelovic** 2024-06-12 06:24 UTC

**Comment by kamranayub** [comment] 2024-12-06 17:00
I think the problem stems from gpt-researcher getting started suggesting to install Python for MacOS from the official site (installer), versus using `brew install python` (or reinstall).

The weasyprint site suggests a pretty simple fix if that's the case:

```
export DYLD_FALLBACK_LIBRARY_PATH=/opt/homebrew/lib:$DYLD_FALLBACK_LIBRARY_PATH
```

This makes Homebrew libs available to the dependency search path. That fixed it for me 👍 

I think the "best practice" is to use Python using Homebrew + venv. I'm a Python noob though, so was just following instructions.

https://github.com/Kozea/WeasyPrint/issues/1556#issuecomment-1123280494

**Comment by maharshivyas** [comment] 2025-01-27 13:19
Thanks @kamranayub your solution works
