### ISSUE TITLE
RETRIVER setting

### ISSUE THREAD

**Issue by peiyaoli** [assafelovic/gpt-researcher#922] opened 2024-10-18 06:45 UTC
**Describe the bug**
It looks like we cannot set RETRIVER solely to `duckduckgo` or others.

It always throw an exception about `Exception: Tavily API key not found. Please set the TAVILY_API_KEY environment variable.`

**Comment by danieldekay** [comment] 2024-10-18 13:26
How did you set it?

**Comment by assafelovic** [comment] 2024-10-18 14:17
Hey @peiyaoli can you try now? I just pushed a fix here: https://github.com/assafelovic/gpt-researcher/pull/924

Please pull latest version

**Comment by ntheodorg** [comment] 2024-10-19 09:27
the issue is still ongoing, even with using the latest commits

**Comment by assafelovic** [comment] 2024-10-19 09:32
Did you set RETRIEVER=duckduckgo?

**Comment by ntheodorg** [comment] 2024-10-19 09:35
i have followed the instructions from https://docs.gptr.dev/docs/gpt-researcher/getting-started/getting-started
There is no information on RETRIEVER and I want to use the default, TAVILY

**Comment by assafelovic** [comment] 2024-10-19 10:41
You're right there was a bug. Just merged a HUGE PR that also includes a fix for that: https://github.com/assafelovic/gpt-researcher/pull/925

**Comment by assafelovic** [comment] 2024-10-19 10:41
Please pull and try again

**Comment by assafelovic** [comment] 2024-10-20 05:35
@ntheodorg can you please update if it's resolved?

**Comment by ntheodorg** [comment] 2024-10-21 05:35
yup, it solved my observed issue

**Closed** 2024-11-03 11:19 UTC
